# Generated by Django 6.0.3 on 2026-03-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('CampaignID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Target_Amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('DonorID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Total_Donated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('Propensity_Score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('VolunteerID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Skills', models.TextField(help_text='Comma-separated skills')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('DonationID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('Payment_Method', models.CharField(choices=[('CC', 'Credit Card'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash')], max_length=20)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('CampaignID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='core_app.campaign')),
                ('DonorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core_app.donor')),
            ],
        ),
    ]
