# Generated by Django 6.0.3 on 2026-03-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='Phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='Preferred_Communication',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('MAIL', 'Mail')], default='EMAIL', max_length=10),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='CampaignID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='core_app.campaign'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Hours_Worked',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
