# Generated by Django 6.0.3 on 2026-04-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_donor_address_donor_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='End_Date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='Status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
