# Generated by Django 6.0.3 on 2026-04-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='Impact_Statement',
            field=models.TextField(blank=True, help_text='What was achieved after this campaign was completed.', null=True),
        ),
    ]
